=== Leomaradan/leomaradan-2022/config/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "CVSection": {
      "additionalProperties": false,
      "properties": {
        "content": {
          "type": "string"
        },
        "order": {
          "type": "number"
        },
        "title": {
          "type": "string"
        }
      },
      "required": ["content", "order", "title"],
      "type": "object"
    },
    "Gallery": {
      "additionalProperties": false,
      "properties": {
        "cover": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "metadata": {
          "additionalProperties": false,
          "properties": {
            "date": {
              "type": "number"
            },
            "description": {
              "type": "string"
            },
            "location": {
              "additionalProperties": false,
              "properties": {
                "latitude": {
                  "type": "number"
                },
                "longitude": {
                  "type": "number"
                }
              },
              "required": ["latitude", "longitude"],
              "type": "object"
            }
          },
          "type": "object"
        },
        "pictures": {
          "items": {
            "$ref": "#/definitions/Picture"
          },
          "type": "array"
        },
        "title": {
          "type": "string"
        }
      },
      "required": ["cover", "id", "pictures", "title"],
      "type": "object"
    },
    "Link": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "order": {
          "type": "number"
        },
        "title": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["order", "title", "url"],
      "type": "object"
    },
    "Picture": {
      "additionalProperties": false,
      "properties": {
        "date": {
          "type": "number"
        },
        "id": {
          "type": "string"
        },
        "metadata": {
          "additionalProperties": false,
          "properties": {
            "description": {
              "type": "string"
            },
            "license": {
              "type": "string"
            },
            "location": {
              "additionalProperties": false,
              "properties": {
                "latitude": {
                  "type": "number"
                },
                "longitude": {
                  "type": "number"
                }
              },
              "required": ["latitude", "longitude"],
              "type": "object"
            }
          },
          "type": "object"
        },
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": ["date", "id", "name", "url"],
      "type": "object"
    }
  },
  "properties": {
    "cv": {
      "items": {
        "$ref": "#/definitions/CVSection"
      },
      "type": "array"
    },
    "galleries": {
      "items": {
        "$ref": "#/definitions/Gallery"
      },
      "type": "array"
    },
    "home": {
      "type": "string"
    },
    "links": {
      "items": {
        "$ref": "#/definitions/Link"
      },
      "type": "array"
    }
  },
  "required": ["cv", "galleries", "home", "links"],
  "type": "object"
}

=== Leomaradan/leomaradan-2022/public/data.json
{
  "cv": [
    {
      "content": "# 2017 - 2018 \r\n## Développements Freelance\r\n\r\n- Développement de templates et d’extensions WordPress, mise\r\nen place d’un site WordPress de podcast audio avec liaison\r\niTunes\r\n- Développement d’une application « bibliothèque » avec\r\nAngular 2 + ExpressJS\r\n- Développement Frontend avec React (site vitrine d’art)\r\n- Création de sites avec Laravel + VueJS, interactions\r\nbidirectionnelles du site avec Twitter (lecture et écriture de\r\ntweet depuis l’application Laravel)",
      "order": 0,
      "title": "Expérience"
    }
  ],
  "galleries": [
    {
      "cover": "url.png",
      "id": "islande-2021",
      "metadata": {
        "description": "Islande 2021",
        "location": {
          "latitude": 0,
          "longitude": 0
        }
      },
      "pictures": [
        {
          "date": 0,
          "id": "image-1",
          "name": "First Picture of Islande 2021",
          "url": "url.png"
        }
      ],
      "title": "Islande 2021"
    }
  ],
  "home": "Accueil",
  "links": [
    {
      "order": 0,
      "title": "LinkedIn",
      "url": "https://www.linkedin.com/in/leomaradan"
    }
  ]
}
